name: Rego (OPA Policy) Unit Tests
run-name: ${{ github.actor }} is running Rego (OPA Policy) unit test Actions 🚀
on: [push]
jobs:
  Run-OPA-Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2
      with:
        version: latest

    - name: Run OPA Tests
      working-directory: ./authorising-api-requests
      run: opa test . -v
                
                
